/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MembersViewMembersRouteImport } from './routes/members/view-members'
import { Route as MembersAddMembersRouteImport } from './routes/members/add-members'
import { Route as MembersMemberIdRouteImport } from './routes/members/$memberId'
import { Route as DeviceViewDeviceRouteImport } from './routes/device/view-device'
import { Route as DeviceAddDeviceRouteImport } from './routes/device/add-device'
import { Route as DeviceDeviceIdRouteImport } from './routes/device/$deviceId'
import { Route as MembersMemberEditMemberIdRouteImport } from './routes/members/memberEdit/$memberId'
import { Route as DeviceDeviceEditDeviceIdRouteImport } from './routes/device/deviceEdit/$deviceId'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersViewMembersRoute = MembersViewMembersRouteImport.update({
  id: '/members/view-members',
  path: '/members/view-members',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersAddMembersRoute = MembersAddMembersRouteImport.update({
  id: '/members/add-members',
  path: '/members/add-members',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersMemberIdRoute = MembersMemberIdRouteImport.update({
  id: '/members/$memberId',
  path: '/members/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceViewDeviceRoute = DeviceViewDeviceRouteImport.update({
  id: '/device/view-device',
  path: '/device/view-device',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceAddDeviceRoute = DeviceAddDeviceRouteImport.update({
  id: '/device/add-device',
  path: '/device/add-device',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceDeviceIdRoute = DeviceDeviceIdRouteImport.update({
  id: '/device/$deviceId',
  path: '/device/$deviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersMemberEditMemberIdRoute =
  MembersMemberEditMemberIdRouteImport.update({
    id: '/members/memberEdit/$memberId',
    path: '/members/memberEdit/$memberId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeviceDeviceEditDeviceIdRoute =
  DeviceDeviceEditDeviceIdRouteImport.update({
    id: '/device/deviceEdit/$deviceId',
    path: '/device/deviceEdit/$deviceId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/test': typeof TestRoute
  '/device/$deviceId': typeof DeviceDeviceIdRoute
  '/device/add-device': typeof DeviceAddDeviceRoute
  '/device/view-device': typeof DeviceViewDeviceRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/members/add-members': typeof MembersAddMembersRoute
  '/members/view-members': typeof MembersViewMembersRoute
  '/device/deviceEdit/$deviceId': typeof DeviceDeviceEditDeviceIdRoute
  '/members/memberEdit/$memberId': typeof MembersMemberEditMemberIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/test': typeof TestRoute
  '/device/$deviceId': typeof DeviceDeviceIdRoute
  '/device/add-device': typeof DeviceAddDeviceRoute
  '/device/view-device': typeof DeviceViewDeviceRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/members/add-members': typeof MembersAddMembersRoute
  '/members/view-members': typeof MembersViewMembersRoute
  '/device/deviceEdit/$deviceId': typeof DeviceDeviceEditDeviceIdRoute
  '/members/memberEdit/$memberId': typeof MembersMemberEditMemberIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/test': typeof TestRoute
  '/device/$deviceId': typeof DeviceDeviceIdRoute
  '/device/add-device': typeof DeviceAddDeviceRoute
  '/device/view-device': typeof DeviceViewDeviceRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/members/add-members': typeof MembersAddMembersRoute
  '/members/view-members': typeof MembersViewMembersRoute
  '/device/deviceEdit/$deviceId': typeof DeviceDeviceEditDeviceIdRoute
  '/members/memberEdit/$memberId': typeof MembersMemberEditMemberIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/test'
    | '/device/$deviceId'
    | '/device/add-device'
    | '/device/view-device'
    | '/members/$memberId'
    | '/members/add-members'
    | '/members/view-members'
    | '/device/deviceEdit/$deviceId'
    | '/members/memberEdit/$memberId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/test'
    | '/device/$deviceId'
    | '/device/add-device'
    | '/device/view-device'
    | '/members/$memberId'
    | '/members/add-members'
    | '/members/view-members'
    | '/device/deviceEdit/$deviceId'
    | '/members/memberEdit/$memberId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/test'
    | '/device/$deviceId'
    | '/device/add-device'
    | '/device/view-device'
    | '/members/$memberId'
    | '/members/add-members'
    | '/members/view-members'
    | '/device/deviceEdit/$deviceId'
    | '/members/memberEdit/$memberId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  TestRoute: typeof TestRoute
  DeviceDeviceIdRoute: typeof DeviceDeviceIdRoute
  DeviceAddDeviceRoute: typeof DeviceAddDeviceRoute
  DeviceViewDeviceRoute: typeof DeviceViewDeviceRoute
  MembersMemberIdRoute: typeof MembersMemberIdRoute
  MembersAddMembersRoute: typeof MembersAddMembersRoute
  MembersViewMembersRoute: typeof MembersViewMembersRoute
  DeviceDeviceEditDeviceIdRoute: typeof DeviceDeviceEditDeviceIdRoute
  MembersMemberEditMemberIdRoute: typeof MembersMemberEditMemberIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/view-members': {
      id: '/members/view-members'
      path: '/members/view-members'
      fullPath: '/members/view-members'
      preLoaderRoute: typeof MembersViewMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/add-members': {
      id: '/members/add-members'
      path: '/members/add-members'
      fullPath: '/members/add-members'
      preLoaderRoute: typeof MembersAddMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$memberId': {
      id: '/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof MembersMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device/view-device': {
      id: '/device/view-device'
      path: '/device/view-device'
      fullPath: '/device/view-device'
      preLoaderRoute: typeof DeviceViewDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device/add-device': {
      id: '/device/add-device'
      path: '/device/add-device'
      fullPath: '/device/add-device'
      preLoaderRoute: typeof DeviceAddDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device/$deviceId': {
      id: '/device/$deviceId'
      path: '/device/$deviceId'
      fullPath: '/device/$deviceId'
      preLoaderRoute: typeof DeviceDeviceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/memberEdit/$memberId': {
      id: '/members/memberEdit/$memberId'
      path: '/members/memberEdit/$memberId'
      fullPath: '/members/memberEdit/$memberId'
      preLoaderRoute: typeof MembersMemberEditMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device/deviceEdit/$deviceId': {
      id: '/device/deviceEdit/$deviceId'
      path: '/device/deviceEdit/$deviceId'
      fullPath: '/device/deviceEdit/$deviceId'
      preLoaderRoute: typeof DeviceDeviceEditDeviceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  TestRoute: TestRoute,
  DeviceDeviceIdRoute: DeviceDeviceIdRoute,
  DeviceAddDeviceRoute: DeviceAddDeviceRoute,
  DeviceViewDeviceRoute: DeviceViewDeviceRoute,
  MembersMemberIdRoute: MembersMemberIdRoute,
  MembersAddMembersRoute: MembersAddMembersRoute,
  MembersViewMembersRoute: MembersViewMembersRoute,
  DeviceDeviceEditDeviceIdRoute: DeviceDeviceEditDeviceIdRoute,
  MembersMemberEditMemberIdRoute: MembersMemberEditMemberIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
